# Generated by Django 4.2 on 2024-11-18 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_enrollment_unique_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enroll_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
