# Generated by Django 4.2 on 2024-11-18 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_enrollment_enroll_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='prerequisite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_courses', to='core.course'),
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2000, '2000학년도'), (2001, '2001학년도'), (2002, '2002학년도'), (2003, '2003학년도'), (2004, '2004학년도'), (2005, '2005학년도'), (2006, '2006학년도'), (2007, '2007학년도'), (2008, '2008학년도'), (2009, '2009학년도'), (2010, '2010학년도'), (2011, '2011학년도'), (2012, '2012학년도'), (2013, '2013학년도'), (2014, '2014학년도'), (2015, '2015학년도'), (2016, '2016학년도'), (2017, '2017학년도'), (2018, '2018학년도'), (2019, '2019학년도'), (2020, '2020학년도'), (2021, '2021학년도'), (2022, '2022학년도'), (2023, '2023학년도'), (2024, '2024학년도'), (2025, '2025학년도'), (2026, '2026학년도'), (2027, '2027학년도'), (2028, '2028학년도'), (2029, '2029학년도'), (2030, '2030학년도'), (2031, '2031학년도'), (2032, '2032학년도'), (2033, '2033학년도'), (2034, '2034학년도'), (2035, '2035학년도'), (2036, '2036학년도'), (2037, '2037학년도'), (2038, '2038학년도'), (2039, '2039학년도'), (2040, '2040학년도'), (2041, '2041학년도'), (2042, '2042학년도'), (2043, '2043학년도'), (2044, '2044학년도'), (2045, '2045학년도'), (2046, '2046학년도'), (2047, '2047학년도'), (2048, '2048학년도'), (2049, '2049학년도'), (2050, '2050학년도'), (2051, '2051학년도'), (2052, '2052학년도'), (2053, '2053학년도'), (2054, '2054학년도'), (2055, '2055학년도'), (2056, '2056학년도'), (2057, '2057학년도'), (2058, '2058학년도'), (2059, '2059학년도'), (2060, '2060학년도'), (2061, '2061학년도'), (2062, '2062학년도'), (2063, '2063학년도'), (2064, '2064학년도'), (2065, '2065학년도'), (2066, '2066학년도'), (2067, '2067학년도'), (2068, '2068학년도'), (2069, '2069학년도'), (2070, '2070학년도'), (2071, '2071학년도'), (2072, '2072학년도'), (2073, '2073학년도'), (2074, '2074학년도'), (2075, '2075학년도'), (2076, '2076학년도'), (2077, '2077학년도'), (2078, '2078학년도'), (2079, '2079학년도'), (2080, '2080학년도'), (2081, '2081학년도'), (2082, '2082학년도'), (2083, '2083학년도'), (2084, '2084학년도'), (2085, '2085학년도'), (2086, '2086학년도'), (2087, '2087학년도'), (2088, '2088학년도'), (2089, '2089학년도'), (2090, '2090학년도'), (2091, '2091학년도'), (2092, '2092학년도'), (2093, '2093학년도'), (2094, '2094학년도'), (2095, '2095학년도'), (2096, '2096학년도'), (2097, '2097학년도'), (2098, '2098학년도'), (2099, '2099학년도'), (2100, '2100학년도')])),
                ('semester', models.CharField(choices=[('1', '1학기'), ('2', '2학기'), ('S', '하계학기'), ('W', '동계학기')], max_length=1)),
            ],
            options={
                'verbose_name': '학기',
                'db_table': 'semester',
                'unique_together': {('year', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='CompletedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A+', '4.3: A+'), ('A', '4.0: A'), ('A-', '3.7: A-'), ('B+', '3.3: B+'), ('B', '3.0: B'), ('B-', '2.7: B-'), ('C+', '2.3: C+'), ('C', '2.0: C'), ('C-', '1.7: C-'), ('D+', '1.3: D+'), ('D', '1.0: D'), ('F', '0.0: F')], max_length=2)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.student')),
            ],
            options={
                'verbose_name': '이수 과목',
                'db_table': 'completed_course',
            },
        ),
    ]
