# Generated by Django 4.2 on 2024-11-18 05:18

from django.db import migrations

def create_semester_data(apps, schema_editor):
    Semester = apps.get_model("core", "Semester")
    semester_data = [
        {"year": 2023, "semester": "1"},  # 2023학년도 1학기
        {"year": 2023, "semester": "2"},  # 2023학년도 2학기
        {"year": 2023, "semester": "S"},  # 2023학년도 하계학기
        {"year": 2023, "semester": "W"},  # 2023학년도 동계학기
        {"year": 2024, "semester": "1"},  # 2024학년도 1학기
        {"year": 2024, "semester": "2"},  # 2024학년도 2학기
    ]
    for data in semester_data:
        Semester.objects.create(**data)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_course_prerequisite_semester_completedcourse'),
    ]

    operations = [
        migrations.RunPython(create_semester_data),
    ]