# Generated by Django 4.2 on 2024-11-18 05:19

from django.db import migrations


def add_completed_courses(apps, schema_editor):
    CompletedCourse = apps.get_model("core", "CompletedCourse")
    Semester = apps.get_model("core", "Semester")

    semester = Semester.objects.get(year=2024, semester="1")

    # 학생 1과 2의 이수 과목 추가
    completed_courses = [
        {"student_id": 1, "course_id": 1, "semester": semester, "grade": "A+"},
        {"student_id": 1, "course_id": 2, "semester": semester, "grade": "A"},
        {"student_id": 1, "course_id": 3, "semester": semester, "grade": "B+"},
        {"student_id": 1, "course_id": 4, "semester": semester, "grade": "B"},
        {"student_id": 1, "course_id": 5, "semester": semester, "grade": "C+"},
        {"student_id": 2, "course_id": 1, "semester": semester, "grade": "A-"},
        {"student_id": 2, "course_id": 2, "semester": semester, "grade": "B+"},
        {"student_id": 2, "course_id": 3, "semester": semester, "grade": "B"},
        {"student_id": 2, "course_id": 4, "semester": semester, "grade": "C"},
        {"student_id": 2, "course_id": 5, "semester": semester, "grade": "F"},
    ]

    for course in completed_courses:
        CompletedCourse.objects.create(**course)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20241118_1418'),
    ]

    operations = [
        migrations.RunPython(add_completed_courses),
    ]
